### ISSUE TITLE
TypeError: Object #<Test> has no method 'callback' on failing tests

### ISSUE THREAD

**Issue by bpasero** [visionmedia/expresso#140]
I am using expresso 0.9.2 and whenever a test is failing I am seeing the following error on each test case that is failing:

   uncaught undefined: TypeError: Object #<Test> has no method 'callback'
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/expresso/bin/expresso:525:26)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1231:22)
    at Socket._onReadable (net.js:677:27)
    at IOWatcher.onReadable [as callback](net.js:177:10)

TypeError: Object #<Test> has no method 'callback'
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/expresso/bin/expresso:525:26)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1231:22)
    at Socket._onReadable (net.js:677:27)
    at IOWatcher.onReadable [as callback](net.js:177:10)

This makes it harder to actually see the stacktrace from the failing test. I can workaround this issue by adding a method "callback" from within my test, but I am not sure whats the purpose of this callback is.

**Comment by isidorn** [comment]
Love the progress here ^_^
